test1 (test.test_1.test)
测试首页的小入口个数 ... FAIL
test2 (test.test_1.test)
ceshi nihao ... FAIL
test (test.test_1.tew) ... ok

======================================================================
FAIL: test1 (test.test_1.test)
测试首页的小入口个数
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\xz\appium_auto_test\test\test_1.py", line 10, in test1
    self.assertEquals(1,2)
AssertionError: 1 != 2

======================================================================
FAIL: test2 (test.test_1.test)
ceshi nihao
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\xz\appium_auto_test\test\test_1.py", line 14, in test2
    self.assertEquals(2,1)
AssertionError: 2 != 1

----------------------------------------------------------------------
Ran 3 tests in 0.005s

FAILED (failures=2)
